### ISSUE TITLE
TOC numbering is single column

### ISSUE THREAD

**Issue by gitscosh** [mholdg16/typora-theme-tokyo-night#2]
I've opened up the CSS, but I'm not very familiar with Typora theming. I love this theme, except that if I have a TOC that goes further than 9 entries, the double digit numbers end up in a single column, and I can't figure out how to widen that column or remove the numbers.

<img width="203" alt="CleanShot 2021-10-07 at 23 37 02@2x" src="https://user-images.githubusercontent.com/22227871/136509992-72e40559-ab26-43fa-95b0-0737a38ff01b.png">

**Comment by Aemiii91** [comment]
This should be fixed now
